#!/usr/bin/env python3
"""
Quick artifact repair utility for defensibility outputs.

This script only derives `clustering_positioning.json` from existing
`k_comparison.json` generated by train_binary_v2_no_bp.py. It does not fabricate metrics.
"""

import json
from pathlib import Path

MODELS_DIR = Path("models/clinical_3class")
RESULTS_DIR = MODELS_DIR / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)


def generate_clustering_positioning():
    """Generate clustering positioning from real k_comparison metrics."""
    print("\n[1/1] Generating clustering positioning from k_comparison.json ...")

    k_comparison_path = RESULTS_DIR / "k_comparison.json"
    if not k_comparison_path.exists():
        raise FileNotFoundError(
            f"{k_comparison_path} not found. Run Ian_ML/training/train_binary_v2_no_bp.py first."
        )

    with k_comparison_path.open("r", encoding="utf-8") as f:
        k_report = json.load(f)

    k_metrics = k_report.get("k_metrics", [])
    if not k_metrics:
        raise ValueError("k_comparison.json has no k_metrics; cannot derive positioning.")

    by_k = {int(item["k"]): item for item in k_metrics if "k" in item}
    if len(by_k) == 0:
        raise ValueError("k_comparison.json has malformed k_metrics entries.")

    best_k = int(max(by_k.values(), key=lambda r: float(r.get("silhouette", -999.0)))["k"])
    clinical_k = int(k_report.get("clinical_k", 4))

    best_sil = float(by_k.get(best_k, {}).get("silhouette", 0.0))
    clinical_sil = float(by_k.get(clinical_k, {}).get("silhouette", best_sil))
    delta_sil = best_sil - clinical_sil

    positioning = {
        "primary_unsupervised": {
            "k": best_k,
            "basis": f"Best unsupervised compactness/separation by silhouette ({best_sil:.6f}).",
            "recommendation": "Present as primary clustering finding"
        },
        "exploratory_clinical_mapping": {
            "k": clinical_k,
            "basis": "Clinically interpretable risk stratification aligned to 4 groups.",
            "recommendation": "Present as exploratory clinical mapping for interpretability"
        },
        "recommended_thesis_wording": (
            f"Primary finding: K={best_k} by silhouette optimization. "
            f"Exploratory analysis: K={clinical_k} mapping for clinical interpretability."
        ),
        "silhouette_comparison": {
            "optimal_k": best_k,
            "optimal_k_silhouette": best_sil,
            "clinical_k": clinical_k,
            "clinical_k_silhouette": clinical_sil,
            "delta_optimal_minus_clinical": delta_sil
        }
    }

    with (RESULTS_DIR / "clustering_positioning.json").open("w", encoding="utf-8") as f:
        json.dump(positioning, f, indent=2)

    print("   ✓ Saved clustering_positioning.json")
    return positioning


def main():
    print("=" * 70)
    print("QUICK ARTIFACT GENERATOR")
    print("Generating clustering positioning from existing artifacts")
    print("=" * 70)

    generate_clustering_positioning()

    print("\n" + "=" * 70)
    print("DONE - Core artifacts generated!")
    print("=" * 70)
    print(f"\nNew files created in: {RESULTS_DIR}")
    print("  ✓ clustering_positioning.json")
    print("\nNote: Full defensibility outputs still come from train_binary_v2_no_bp.py.")


if __name__ == "__main__":
    main()
