// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"github.com/swaggo/swag"
)

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "DIANA Support",
            "email": "support@diana-health.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate user and return JWT tokens",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Authentication"],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {"type": "string", "example": "user@example.com"},
                                "password": {"type": "string", "example": "password123"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful with tokens"
                    },
                    "401": {
                        "description": "Invalid credentials"
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Create a new user account",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Authentication"],
                "summary": "Register new user",
                "parameters": [
                    {
                        "description": "Registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {"type": "string", "example": "user@example.com"},
                                "password": {"type": "string", "example": "password123"},
                                "name": {"type": "string", "example": "John Doe"}
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully"
                    },
                    "400": {
                        "description": "Invalid input"
                    }
                }
            }
        },
        "/patients": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get all patients for the authenticated user",
                "produces": ["application/json"],
                "tags": ["Patients"],
                "summary": "List all patients",
                "responses": {
                    "200": {
                        "description": "List of patients"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Create a new patient record",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Patients"],
                "summary": "Create patient",
                "parameters": [
                    {
                        "description": "Patient data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string"},
                                "age": {"type": "integer"},
                                "bmi": {"type": "number"},
                                "bp_systolic": {"type": "integer"},
                                "bp_diastolic": {"type": "integer"}
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Patient created"
                    }
                }
            }
        },
        "/patients/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get a specific patient by ID",
                "produces": ["application/json"],
                "tags": ["Patients"],
                "summary": "Get patient",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Patient data"
                    },
                    "404": {
                        "description": "Patient not found"
                    }
                }
            },
            "put": {
                "security": [{"BearerAuth": []}],
                "description": "Update a patient record",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Patients"],
                "summary": "Update patient",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Patient updated"
                    }
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "description": "Delete a patient record",
                "tags": ["Patients"],
                "summary": "Delete patient",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Patient deleted"
                    }
                }
            }
        },
        "/patients/{id}/assessments": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get all assessments for a patient",
                "produces": ["application/json"],
                "tags": ["Assessments"],
                "summary": "List patient assessments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of assessments"
                    }
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Create a new diabetes risk assessment with ML prediction",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Assessments"],
                "summary": "Create assessment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Assessment data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "fbs": {"type": "number", "description": "Fasting Blood Sugar (mg/dL)"},
                                "hba1c": {"type": "number", "description": "HbA1c percentage"},
                                "cholesterol": {"type": "integer"},
                                "ldl": {"type": "integer"},
                                "hdl": {"type": "integer"},
                                "triglycerides": {"type": "integer"},
                                "systolic": {"type": "integer"},
                                "diastolic": {"type": "integer"},
                                "bmi": {"type": "number"}
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Assessment created with risk prediction"
                    }
                }
            }
        },
        "/insights/clusters": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get cluster distribution insights",
                "produces": ["application/json"],
                "tags": ["Insights"],
                "summary": "Get cluster insights",
                "responses": {
                    "200": {
                        "description": "Cluster distribution data"
                    }
                }
            }
        },
        "/insights/trends": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get trend averages over time",
                "produces": ["application/json"],
                "tags": ["Insights"],
                "summary": "Get trend insights",
                "responses": {
                    "200": {
                        "description": "Trend data"
                    }
                }
            }
        },
        "/export/patients": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Export patient data as CSV",
                "produces": ["text/csv"],
                "tags": ["Export"],
                "summary": "Export patients",
                "responses": {
                    "200": {
                        "description": "CSV file download"
                    }
                }
            }
        },
        "/export/assessments": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Export assessment data as CSV",
                "produces": ["text/csv"],
                "tags": ["Export"],
                "summary": "Export assessments",
                "responses": {
                    "200": {
                        "description": "CSV file download"
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check API health status",
                "produces": ["application/json"],
                "tags": ["Health"],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "API is healthy"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Bearer token. Format: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "DIANA API",
	Description:      "Diabetes Insulin Activity and Nutrition Analyzer (DIANA) - Risk assessment and patient management API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
