// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patients.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (
  name, age, menopause_status, years_menopause, bmi, bp_systolic, bp_diastolic,
  activity, phys_activity, smoking, hypertension, heart_disease, family_history, chol, ldl, hdl, triglycerides
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, name, age, menopause_status, years_menopause, bmi, bp_systolic, bp_diastolic,
          activity, phys_activity, smoking, hypertension, heart_disease, family_history, chol, ldl, hdl, triglycerides,
          created_at, updated_at
`

type CreatePatientParams struct {
	Name            string         `json:"name"`
	Age             pgtype.Int4    `json:"age"`
	MenopauseStatus pgtype.Text    `json:"menopause_status"`
	YearsMenopause  pgtype.Int4    `json:"years_menopause"`
	Bmi             pgtype.Numeric `json:"bmi"`
	BpSystolic      pgtype.Int4    `json:"bp_systolic"`
	BpDiastolic     pgtype.Int4    `json:"bp_diastolic"`
	Activity        pgtype.Text    `json:"activity"`
	PhysActivity    pgtype.Bool    `json:"phys_activity"`
	Smoking         pgtype.Text    `json:"smoking"`
	Hypertension    pgtype.Text    `json:"hypertension"`
	HeartDisease    pgtype.Text    `json:"heart_disease"`
	FamilyHistory   pgtype.Bool    `json:"family_history"`
	Chol            pgtype.Int4    `json:"chol"`
	Ldl             pgtype.Int4    `json:"ldl"`
	Hdl             pgtype.Int4    `json:"hdl"`
	Triglycerides   pgtype.Int4    `json:"triglycerides"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.Name,
		arg.Age,
		arg.MenopauseStatus,
		arg.YearsMenopause,
		arg.Bmi,
		arg.BpSystolic,
		arg.BpDiastolic,
		arg.Activity,
		arg.PhysActivity,
		arg.Smoking,
		arg.Hypertension,
		arg.HeartDisease,
		arg.FamilyHistory,
		arg.Chol,
		arg.Ldl,
		arg.Hdl,
		arg.Triglycerides,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Age,
		&i.MenopauseStatus,
		&i.YearsMenopause,
		&i.Bmi,
		&i.BpSystolic,
		&i.BpDiastolic,
		&i.Activity,
		&i.PhysActivity,
		&i.Smoking,
		&i.Hypertension,
		&i.HeartDisease,
		&i.FamilyHistory,
		&i.Chol,
		&i.Ldl,
		&i.Hdl,
		&i.Triglycerides,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPatients = `-- name: ListPatients :many
SELECT id, name, age, menopause_status, years_menopause, bmi, bp_systolic, bp_diastolic,
       activity, phys_activity, smoking, hypertension, heart_disease, family_history, chol, ldl, hdl, triglycerides,
       created_at, updated_at
FROM patients
ORDER BY id DESC
`

func (q *Queries) ListPatients(ctx context.Context) ([]Patient, error) {
	rows, err := q.db.Query(ctx, listPatients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patient
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.MenopauseStatus,
			&i.YearsMenopause,
			&i.Bmi,
			&i.BpSystolic,
			&i.BpDiastolic,
			&i.Activity,
			&i.PhysActivity,
			&i.Smoking,
			&i.Hypertension,
			&i.HeartDisease,
			&i.FamilyHistory,
			&i.Chol,
			&i.Ldl,
			&i.Hdl,
			&i.Triglycerides,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientsLimited = `-- name: ListPatientsLimited :many
SELECT id, name, age, menopause_status, years_menopause, bmi, bp_systolic, bp_diastolic,
       activity, phys_activity, smoking, hypertension, heart_disease, family_history, chol, ldl, hdl, triglycerides,
       created_at, updated_at
FROM patients
ORDER BY id DESC
LIMIT $1
`

func (q *Queries) ListPatientsLimited(ctx context.Context, limit int32) ([]Patient, error) {
	rows, err := q.db.Query(ctx, listPatientsLimited, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patient
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.MenopauseStatus,
			&i.YearsMenopause,
			&i.Bmi,
			&i.BpSystolic,
			&i.BpDiastolic,
			&i.Activity,
			&i.PhysActivity,
			&i.Smoking,
			&i.Hypertension,
			&i.HeartDisease,
			&i.FamilyHistory,
			&i.Chol,
			&i.Ldl,
			&i.Hdl,
			&i.Triglycerides,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
