package services

import (
	"bytes"
	"fmt"
	"math/rand"
	"time"

	"github.com/go-pdf/fpdf"
	"github.com/skufu/DianaV2/backend/internal/models"
)

// Professional Medical Color Palette
var (
	textDark    = [3]int{30, 41, 59}    // Slate-800
	textLight   = [3]int{100, 116, 139} // Slate-500
	primary     = [3]int{15, 23, 42}    // Slate-900
	accent      = [3]int{59, 130, 246}  // Blue-500
	bgLight     = [3]int{248, 250, 252} // Slate-50
	borderLight = [3]int{226, 232, 240} // Slate-200

	success = [3]int{22, 163, 74} // Green-600
	warning = [3]int{234, 179, 8} // Yellow-500
	danger  = [3]int{220, 38, 38} // Red-600
)

type PDFExportService struct{}

type PDFExportOptions struct {
	UserID        int64
	UserName      string
	UserEmail     string
	Assessments   []models.Assessment
	IncludeCharts bool
	FormatDate    time.Time
}

func NewPDFExportService() *PDFExportService {
	return &PDFExportService{}
}

// GenerateMockData creates realistic mock data for PDF testing
func GenerateMockData() (models.UserProfile, []models.Assessment) {
	dob := time.Date(1968, 5, 15, 0, 0, 0, 0, time.UTC)
	user := models.UserProfile{
		User: models.User{
			ID:              1,
			Email:           "maria.santos@email.com",
			FirstName:       "Maria",
			LastName:        "Santos",
			DateOfBirth:     &dob,
			MenopauseStatus: "post",
			YearsMenopause:  8,
		},
		AssessmentCount:  6,
		CurrentCluster:   "MARD",
		CurrentRiskLevel: "moderate",
	}

	baseTime := time.Now()
	assessments := []models.Assessment{
		{ID: 6, UserID: 1, BMI: 27.4, LDL: 142, HDL: 48, Triglycerides: 168, Cholesterol: 215, Cluster: "MARD", RiskScore: 58, CreatedAt: baseTime},
		{ID: 5, UserID: 1, BMI: 27.8, LDL: 148, HDL: 45, Triglycerides: 175, Cluster: "MARD", RiskScore: 62, CreatedAt: baseTime.AddDate(0, -1, 0)},
		{ID: 4, UserID: 1, BMI: 28.1, LDL: 155, HDL: 44, Triglycerides: 182, Cluster: "SIDD", RiskScore: 68, CreatedAt: baseTime.AddDate(0, -2, 0)},
		{ID: 3, UserID: 1, BMI: 28.5, LDL: 162, HDL: 42, Triglycerides: 195, Cluster: "SIDD", RiskScore: 72, CreatedAt: baseTime.AddDate(0, -4, 0)},
	}
	return user, assessments
}

// GenerateHealthReport generates a readable, multi-page friendly PDF
func (s *PDFExportService) GenerateHealthReport(user models.UserProfile, assessments []models.Assessment) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 15, 15)
	
	// Better page breaking for larger text sections
	pdf.SetAutoPageBreak(true, 15)

	if len(assessments) == 0 {
		user, assessments = GenerateMockData()
	}

	pdf.AddPage()

	// === HEADER ===
	pdf.SetFont("Arial", "B", 26)
	pdf.SetTextColor(primary[0], primary[1], primary[2])
	pdf.CellFormat(80, 12, "DIANA", "", 0, "L", false, 0, "")

	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(textLight[0], textLight[1], textLight[2])
	pdf.CellFormat(0, 12, "Health Report  |  "+time.Now().Format("January 2, 2006"), "", 1, "R", false, 0, "")

	pdf.SetDrawColor(primary[0], primary[1], primary[2])
	pdf.SetLineWidth(0.5)
	pdf.Line(15, pdf.GetY()+2, 195, pdf.GetY()+2)
	pdf.Ln(10)

	// === PATIENT INFO (Larger Text) ===
	fullname := fmt.Sprintf("%s %s", user.FirstName, user.LastName)
	if user.FirstName == "" {
		fullname = user.Email
	}
	age := "N/A"
	if user.DateOfBirth != nil {
		age = fmt.Sprintf("%d yrs", time.Now().Year()-user.DateOfBirth.Year())
	}

	pdf.SetFont("Arial", "B", 14)
	pdf.SetTextColor(textDark[0], textDark[1], textDark[2])
	pdf.CellFormat(0, 8, fmt.Sprintf("Patient: %s", fullname), "", 1, "L", false, 0, "")
	
	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(textLight[0], textLight[1], textLight[2])
	pdf.CellFormat(0, 7, fmt.Sprintf("Age: %s   |   Status: %s   |   ID: #%d", age, casesTitle(user.MenopauseStatus), user.User.ID), "", 1, "L", false, 0, "")
	pdf.Ln(8)

	// === KEY METRICS ===
	if len(assessments) > 0 {
		a := assessments[0]
		
		pdf.SetFont("Arial", "B", 16)
		pdf.SetTextColor(primary[0], primary[1], primary[2])
		pdf.Cell(0, 10, "Summary")
		pdf.Ln(10)
		
		// 2 wide cards instead of 3 cramped ones
		boxW := 85.0
		boxH := 28.0
		gap := 10.0
		y := pdf.GetY()

		s.drawMetricCard(pdf, 15, y, boxW, boxH, "DIABETES RISK SCORE", fmt.Sprintf("%d%%", a.RiskScore), s.getRiskColor(a.RiskScore))
		s.drawMetricCard(pdf, 15+boxW+gap, y, boxW, boxH, "BODY MASS INDEX (BMI)", fmt.Sprintf("%.1f", a.BMI), s.getStatusColor(s.getBMIStatus(a.BMI)))

		pdf.SetY(y + boxH + 12)
	}

	// === BIOMARKER TABLE ===
	if len(assessments) > 0 {
		s.drawBiomarkerTable(pdf, assessments[0])
	}
	pdf.Ln(10)

	// === SINGLE COLUMN SECTIONS ===
	
	// History
	if len(assessments) > 1 {
		s.drawHistorySection(pdf, assessments, 180.0)
		pdf.Ln(10)
	}

	// Care Plan
	if len(assessments) > 0 {
		s.drawCarePlanSection(pdf, assessments[0], 180.0)
	}

	// === FOOTER ===
	pdf.SetY(-20)
	pdf.SetFont("Arial", "", 10)
	pdf.SetTextColor(textLight[0], textLight[1], textLight[2])
	pdf.CellFormat(0, 5, "Generated by DIANA. This report is for informational purposes only.", "", 1, "C", false, 0, "")
	pdf.CellFormat(0, 5, "Please consult with your doctor for medical advice.", "", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("failed to generate PDF: %w", err)
	}
	return buf.Bytes(), nil
}

func (s *PDFExportService) drawMetricCard(pdf *fpdf.Fpdf, x, y, w, h float64, label, value string, color [3]int) {
	pdf.SetFillColor(bgLight[0], bgLight[1], bgLight[2])
	pdf.SetDrawColor(borderLight[0], borderLight[1], borderLight[2])
	pdf.Rect(x, y, w, h, "FD")

	// Status bar
	pdf.SetFillColor(color[0], color[1], color[2])
	pdf.Rect(x, y, 4, h, "F")

	// Label
	pdf.SetXY(x+8, y+5)
	pdf.SetFont("Arial", "B", 10)
	pdf.SetTextColor(textLight[0], textLight[1], textLight[2])
	pdf.Cell(w-8, 6, label)

	// Value
	pdf.SetXY(x+8, y+12)
	pdf.SetFont("Arial", "B", 20)
	pdf.SetTextColor(textDark[0], textDark[1], textDark[2])
	pdf.Cell(w-8, 12, value)
}

func (s *PDFExportService) drawBiomarkerTable(pdf *fpdf.Fpdf, a models.Assessment) {
	pdf.SetFont("Arial", "B", 16)
	pdf.SetTextColor(primary[0], primary[1], primary[2])
	pdf.Cell(0, 10, "Detailed Results")
	pdf.Ln(10)

	headers := []string{"Test Name", "Result", "Normal Range", "Status"}
	widths := []float64{60, 40, 45, 35}
	aligns := []string{"L", "R", "C", "C"}

	pdf.SetFont("Arial", "B", 11)
	pdf.SetTextColor(textDark[0], textDark[1], textDark[2])
	pdf.SetFillColor(borderLight[0], borderLight[1], borderLight[2])
	
	for i, h := range headers {
		pdf.CellFormat(widths[i], 9, h, "B", 0, aligns[i], true, 0, "")
	}
	pdf.Ln(9)

	rows := []struct{ name, val, ref, status string }{
		{"Total Cholesterol", fmt.Sprintf("%d mg/dL", a.Cholesterol), "< 200", s.getCholStatus(a.Cholesterol)},
		{"HDL (Good Cholesterol)", fmt.Sprintf("%d mg/dL", a.HDL), "> 50", s.getHDLStatus(a.HDL)},
		{"LDL (Bad Cholesterol)", fmt.Sprintf("%d mg/dL", a.LDL), "< 100", s.getLDLStatus(a.LDL)},
		{"Triglycerides", fmt.Sprintf("%d mg/dL", a.Triglycerides), "< 150", s.getTGStatus(a.Triglycerides)},
		{"BMI", fmt.Sprintf("%.1f", a.BMI), "18.5 - 24.9", s.getBMIStatus(a.BMI)},
	}

	pdf.SetFont("Arial", "", 12)
	for _, r := range rows {
		pdf.SetTextColor(textDark[0], textDark[1], textDark[2])
		pdf.CellFormat(widths[0], 9, r.name, "B", 0, "L", false, 0, "")
		
		pdf.SetFont("Arial", "B", 12)
		pdf.CellFormat(widths[1], 9, r.val, "B", 0, "R", false, 0, "")
		pdf.SetFont("Arial", "", 12)
		
		pdf.SetTextColor(textLight[0], textLight[1], textLight[2])
		pdf.CellFormat(widths[2], 9, r.ref, "B", 0, "C", false, 0, "")
		
		c := s.getStatusColor(r.status)
		pdf.SetTextColor(c[0], c[1], c[2])
		pdf.SetFont("Arial", "B", 11)
		pdf.CellFormat(widths[3], 9, r.status, "B", 1, "C", false, 0, "")
		pdf.SetFont("Arial", "", 12)
	}
}

func (s *PDFExportService) drawHistorySection(pdf *fpdf.Fpdf, assessments []models.Assessment, w float64) {
	pdf.SetFont("Arial", "B", 16)
	pdf.SetTextColor(primary[0], primary[1], primary[2])
	pdf.Cell(w, 10, "Your Health History")
	pdf.Ln(10)

	colW := w / 3.0
	pdf.SetFont("Arial", "B", 11)
	pdf.SetTextColor(textDark[0], textDark[1], textDark[2])
	pdf.SetFillColor(borderLight[0], borderLight[1], borderLight[2])
	
	pdf.CellFormat(colW, 8, "Date", "B", 0, "C", true, 0, "")
	pdf.CellFormat(colW, 8, "Risk Score", "B", 0, "C", true, 0, "")
	pdf.CellFormat(colW, 8, "BMI", "B", 1, "C", true, 0, "")

	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(textDark[0], textDark[1], textDark[2])
	maxRows := 5
	if len(assessments) < maxRows {
		maxRows = len(assessments)
	}
	
	for i := 0; i < maxRows; i++ {
		a := assessments[i]
		pdf.CellFormat(colW, 8, a.CreatedAt.Format("Jan 02, 2006"), "B", 0, "C", false, 0, "")
		pdf.CellFormat(colW, 8, fmt.Sprintf("%d%%", a.RiskScore), "B", 0, "C", false, 0, "")
		pdf.CellFormat(colW, 8, fmt.Sprintf("%.1f", a.BMI), "B", 1, "C", false, 0, "")
	}
}

func (s *PDFExportService) drawCarePlanSection(pdf *fpdf.Fpdf, a models.Assessment, w float64) {
	pdf.SetFont("Arial", "B", 16)
	pdf.SetTextColor(primary[0], primary[1], primary[2])
	pdf.Cell(w, 10, "Doctor Discussion Points")
	pdf.Ln(10)

	recs := s.getSmartRecommendations(a)

	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(textDark[0], textDark[1], textDark[2])
	
	for _, rec := range recs {
		pdf.SetTextColor(accent[0], accent[1], accent[2])
		pdf.Cell(8, 8, "\u2022") // bullet point
		pdf.SetTextColor(textDark[0], textDark[1], textDark[2])
		pdf.MultiCell(w-8, 8, rec, "", "L", false)
		pdf.Ln(2)
	}
}

// --- Helpers ---

func casesTitle(s string) string {
	if len(s) == 0 {
		return "N/A"
	}
	if s[0] >= 'a' && s[0] <= 'z' {
		return string(s[0]-32) + s[1:]
	}
	return s
}

func (s *PDFExportService) getStatusColor(status string) [3]int {
	switch status {
	case "Normal":
		return success
	case "Borderline", "Elevated", "Overweight", "Pre-diabetic":
		return warning
	default:
		return danger
	}
}

func (s *PDFExportService) getRiskColor(score int) [3]int {
	if score < 30 {
		return success
	}
	if score < 70 {
		return warning
	}
	return danger
}

func (s *PDFExportService) getSmartRecommendations(a models.Assessment) []string {
	var recs []string
	
	if a.RiskScore >= 70 {
		recs = append(recs, "Your overall high risk score indicates it is important to discuss these results with your doctor soon.")
	}

	if a.BMI >= 30 {
		recs = append(recs, "Weight: Nutritional counseling and a structured weight management plan could significantly improve your health markers.")
	} else if a.BMI >= 25 {
		recs = append(recs, "Weight: Incorporating more physical activity and slight dietary changes can help manage your weight.")
	}
	
	if a.LDL >= 130 || a.Cholesterol >= 200 {
		recs = append(recs, "Cholesterol: Your lipid levels are high. Evaluation for lipid-lowering therapy or dietary changes may be necessary.")
	}

	if len(recs) == 0 {
		recs = append(recs, "Your recent markers are excellent. Continue your healthy lifestyle habits and proceed with your regular annual check-ups.")
	}
	return recs
}

func (s *PDFExportService) getHbA1cStatus(v float64) string {
	if v >= 6.5 {
		return "High"
	}
	if v >= 5.7 {
		return "Pre-diabetic"
	}
	return "Normal"
}
func (s *PDFExportService) getFBSStatus(v float64) string {
	if v >= 126 {
		return "High"
	}
	if v >= 100 {
		return "Elevated"
	}
	return "Normal"
}
func (s *PDFExportService) getBMIStatus(v float64) string {
	if v >= 30 {
		return "Obese"
	}
	if v >= 25 {
		return "Overweight"
	}
	return "Normal"
}
func (s *PDFExportService) getCholStatus(v int) string {
	if v >= 240 {
		return "High"
	}
	if v >= 200 {
		return "Borderline"
	}
	return "Normal"
}
func (s *PDFExportService) getLDLStatus(v int) string {
	if v >= 160 {
		return "High"
	}
	if v >= 130 {
		return "Borderline"
	}
	return "Normal"
}
func (s *PDFExportService) getHDLStatus(v int) string {
	if v < 40 {
		return "Low"
	}
	return "Normal"
}
func (s *PDFExportService) getTGStatus(v int) string {
	if v >= 200 {
		return "High"
	}
	if v >= 150 {
		return "Borderline"
	}
	return "Normal"
}

// Helper for tests
func getRiskLevel(score int32) string {
	if score < 30 {
		return "Low"
	}
	if score < 70 {
		return "Moderate"
	}
	return "High"
}

var _ = rand.Int
