// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_events.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuthEvents = `-- name: CountAuthEvents :one
SELECT COUNT(*)
FROM auth_events
WHERE
    ($1::text = '' OR event_type = $1)
    AND ($2::text = '' OR email ILIKE '%' || $2 || '%')
    AND ($3::timestamptz IS NULL OR created_at >= $3)
    AND ($4::timestamptz IS NULL OR created_at <= $4)
`

type CountAuthEventsParams struct {
	Column1 string             `json:"column_1"`
	Column2 string             `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
	Column4 pgtype.Timestamptz `json:"column_4"`
}

func (q *Queries) CountAuthEvents(ctx context.Context, arg CountAuthEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthEvents,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthEvent = `-- name: CreateAuthEvent :exec
INSERT INTO auth_events (event_type, email, ip_address, user_agent, success, metadata, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
`

type CreateAuthEventParams struct {
	EventType string      `json:"event_type"`
	Email     pgtype.Text `json:"email"`
	IpAddress *netip.Addr `json:"ip_address"`
	UserAgent pgtype.Text `json:"user_agent"`
	Success   bool        `json:"success"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateAuthEvent(ctx context.Context, arg CreateAuthEventParams) error {
	_, err := q.db.Exec(ctx, createAuthEvent,
		arg.EventType,
		arg.Email,
		arg.IpAddress,
		arg.UserAgent,
		arg.Success,
		arg.Metadata,
	)
	return err
}

const getRecentAuthEvents = `-- name: GetRecentAuthEvents :many
SELECT id, event_type, email, ip_address, user_agent, success, device_info, location, metadata, created_at
FROM auth_events
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetRecentAuthEvents(ctx context.Context, limit int32) ([]AuthEvent, error) {
	rows, err := q.db.Query(ctx, getRecentAuthEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthEvent
	for rows.Next() {
		var i AuthEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Email,
			&i.IpAddress,
			&i.UserAgent,
			&i.Success,
			&i.DeviceInfo,
			&i.Location,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthEvents = `-- name: ListAuthEvents :many
SELECT id, event_type, email, ip_address, user_agent, success, device_info, location, metadata, created_at
FROM auth_events
WHERE
    ($1::text = '' OR event_type = $1)
    AND ($2::text = '' OR email ILIKE '%' || $2 || '%')
    AND ($3::timestamptz IS NULL OR created_at >= $3)
    AND ($4::timestamptz IS NULL OR created_at <= $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListAuthEventsParams struct {
	Column1 string             `json:"column_1"`
	Column2 string             `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
	Column4 pgtype.Timestamptz `json:"column_4"`
	Limit   int32              `json:"limit"`
	Offset  int32              `json:"offset"`
}

func (q *Queries) ListAuthEvents(ctx context.Context, arg ListAuthEventsParams) ([]AuthEvent, error) {
	rows, err := q.db.Query(ctx, listAuthEvents,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthEvent
	for rows.Next() {
		var i AuthEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Email,
			&i.IpAddress,
			&i.UserAgent,
			&i.Success,
			&i.DeviceInfo,
			&i.Location,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
