// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clinics.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToClinic = `-- name: AddUserToClinic :exec
INSERT INTO user_clinics (user_id, clinic_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, clinic_id) DO UPDATE SET role = $3
`

type AddUserToClinicParams struct {
	UserID   int32  `json:"user_id"`
	ClinicID int32  `json:"clinic_id"`
	Role     string `json:"role"`
}

func (q *Queries) AddUserToClinic(ctx context.Context, arg AddUserToClinicParams) error {
	_, err := q.db.Exec(ctx, addUserToClinic, arg.UserID, arg.ClinicID, arg.Role)
	return err
}

const createClinic = `-- name: CreateClinic :one
INSERT INTO clinics (name, address)
VALUES ($1, $2)
RETURNING id, name, address, created_at, updated_at
`

type CreateClinicParams struct {
	Name    string      `json:"name"`
	Address pgtype.Text `json:"address"`
}

func (q *Queries) CreateClinic(ctx context.Context, arg CreateClinicParams) (Clinic, error) {
	row := q.db.QueryRow(ctx, createClinic, arg.Name, arg.Address)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClinic = `-- name: DeleteClinic :exec
DELETE FROM clinics WHERE id = $1
`

func (q *Queries) DeleteClinic(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteClinic, id)
	return err
}

const getClinic = `-- name: GetClinic :one
SELECT id, name, address, created_at, updated_at
FROM clinics
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetClinic(ctx context.Context, id int32) (Clinic, error) {
	row := q.db.QueryRow(ctx, getClinic, id)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserClinicRole = `-- name: GetUserClinicRole :one
SELECT role
FROM user_clinics
WHERE user_id = $1 AND clinic_id = $2
LIMIT 1
`

type GetUserClinicRoleParams struct {
	UserID   int32 `json:"user_id"`
	ClinicID int32 `json:"clinic_id"`
}

func (q *Queries) GetUserClinicRole(ctx context.Context, arg GetUserClinicRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserClinicRole, arg.UserID, arg.ClinicID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const isClinicAdmin = `-- name: IsClinicAdmin :one
SELECT EXISTS(
    SELECT 1 FROM user_clinics
    WHERE user_id = $1 AND clinic_id = $2 AND role = 'clinic_admin'
) AS is_admin
`

type IsClinicAdminParams struct {
	UserID   int32 `json:"user_id"`
	ClinicID int32 `json:"clinic_id"`
}

func (q *Queries) IsClinicAdmin(ctx context.Context, arg IsClinicAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, isClinicAdmin, arg.UserID, arg.ClinicID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const listClinicUsers = `-- name: ListClinicUsers :many
SELECT u.id, u.email, u.role AS user_role, uc.role AS clinic_role, u.created_at
FROM users u
JOIN user_clinics uc ON u.id = uc.user_id
WHERE uc.clinic_id = $1
ORDER BY u.email
`

type ListClinicUsersRow struct {
	ID         int32              `json:"id"`
	Email      string             `json:"email"`
	UserRole   string             `json:"user_role"`
	ClinicRole string             `json:"clinic_role"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListClinicUsers(ctx context.Context, clinicID int32) ([]ListClinicUsersRow, error) {
	rows, err := q.db.Query(ctx, listClinicUsers, clinicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClinicUsersRow
	for rows.Next() {
		var i ListClinicUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.UserRole,
			&i.ClinicRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClinics = `-- name: ListClinics :many

SELECT id, name, address, created_at, updated_at
FROM clinics
ORDER BY name
`

// clinics.sql: SQLC queries for clinic management
func (q *Queries) ListClinics(ctx context.Context) ([]Clinic, error) {
	rows, err := q.db.Query(ctx, listClinics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Clinic
	for rows.Next() {
		var i Clinic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserClinics = `-- name: ListUserClinics :many
SELECT c.id, c.name, c.address, c.created_at, c.updated_at, uc.role
FROM clinics c
JOIN user_clinics uc ON c.id = uc.clinic_id
WHERE uc.user_id = $1
ORDER BY c.name
`

type ListUserClinicsRow struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Address   pgtype.Text        `json:"address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Role      string             `json:"role"`
}

func (q *Queries) ListUserClinics(ctx context.Context, userID int32) ([]ListUserClinicsRow, error) {
	rows, err := q.db.Query(ctx, listUserClinics, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserClinicsRow
	for rows.Next() {
		var i ListUserClinicsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromClinic = `-- name: RemoveUserFromClinic :exec
DELETE FROM user_clinics
WHERE user_id = $1 AND clinic_id = $2
`

type RemoveUserFromClinicParams struct {
	UserID   int32 `json:"user_id"`
	ClinicID int32 `json:"clinic_id"`
}

func (q *Queries) RemoveUserFromClinic(ctx context.Context, arg RemoveUserFromClinicParams) error {
	_, err := q.db.Exec(ctx, removeUserFromClinic, arg.UserID, arg.ClinicID)
	return err
}

const updateClinic = `-- name: UpdateClinic :one
UPDATE clinics
SET name = $2, address = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, name, address, created_at, updated_at
`

type UpdateClinicParams struct {
	ID      int32       `json:"id"`
	Name    string      `json:"name"`
	Address pgtype.Text `json:"address"`
}

func (q *Queries) UpdateClinic(ctx context.Context, arg UpdateClinicParams) (Clinic, error) {
	row := q.db.QueryRow(ctx, updateClinic, arg.ID, arg.Name, arg.Address)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
