// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cohort.sql

package sqlcgen

import (
	"context"
)

const cohortStatsByAgeGroup = `-- name: CohortStatsByAgeGroup :many
SELECT 
    CASE 
        WHEN DATE_PART('year', AGE(u.date_of_birth)) < 30 THEN '<30'
        WHEN DATE_PART('year', AGE(u.date_of_birth)) >= 30 AND DATE_PART('year', AGE(u.date_of_birth)) < 50 THEN '30-49'
        WHEN DATE_PART('year', AGE(u.date_of_birth)) >= 50 AND DATE_PART('year', AGE(u.date_of_birth)) < 70 THEN '50-69'
        ELSE '70+'
    END AS group_name,
    COUNT(*)::int AS count,
    COALESCE(AVG(a.hba1c), 0)::float8 AS avg_hba1c,
    COALESCE(AVG(a.fbs), 0)::float8 AS avg_fbs,
    COALESCE(AVG(a.bmi), 0)::float8 AS avg_bmi,
    COALESCE(AVG(a.systolic), 0)::float8 AS avg_bp_systolic,
    COALESCE(AVG(a.diastolic), 0)::float8 AS avg_bp_diastolic,
    COALESCE(AVG(a.risk_score), 0)::float8 AS avg_risk_score
FROM assessments a
JOIN users u ON a.user_id = u.id
GROUP BY 1
`

type CohortStatsByAgeGroupRow struct {
	GroupName      string  `json:"group_name"`
	Count          int32   `json:"count"`
	AvgHba1c       float64 `json:"avg_hba1c"`
	AvgFbs         float64 `json:"avg_fbs"`
	AvgBmi         float64 `json:"avg_bmi"`
	AvgBpSystolic  float64 `json:"avg_bp_systolic"`
	AvgBpDiastolic float64 `json:"avg_bp_diastolic"`
	AvgRiskScore   float64 `json:"avg_risk_score"`
}

func (q *Queries) CohortStatsByAgeGroup(ctx context.Context) ([]CohortStatsByAgeGroupRow, error) {
	rows, err := q.db.Query(ctx, cohortStatsByAgeGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CohortStatsByAgeGroupRow
	for rows.Next() {
		var i CohortStatsByAgeGroupRow
		if err := rows.Scan(
			&i.GroupName,
			&i.Count,
			&i.AvgHba1c,
			&i.AvgFbs,
			&i.AvgBmi,
			&i.AvgBpSystolic,
			&i.AvgBpDiastolic,
			&i.AvgRiskScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cohortStatsByCluster = `-- name: CohortStatsByCluster :many

SELECT 
    COALESCE(cluster, 'Unknown') AS group_name,
    COUNT(*)::int AS count,
    COALESCE(AVG(hba1c), 0)::float8 AS avg_hba1c,
    COALESCE(AVG(fbs), 0)::float8 AS avg_fbs,
    COALESCE(AVG(bmi), 0)::float8 AS avg_bmi,
    COALESCE(AVG(systolic), 0)::float8 AS avg_bp_systolic,
    COALESCE(AVG(diastolic), 0)::float8 AS avg_bp_diastolic,
    COALESCE(AVG(risk_score), 0)::float8 AS avg_risk_score,
    COUNT(CASE WHEN risk_score < 30 THEN 1 END)::int AS low_risk_count,
    COUNT(CASE WHEN risk_score >= 30 AND risk_score < 70 THEN 1 END)::int AS moderate_risk_count,
    COUNT(CASE WHEN risk_score >= 70 THEN 1 END)::int AS high_risk_count
FROM assessments
GROUP BY COALESCE(cluster, 'Unknown')
`

type CohortStatsByClusterRow struct {
	GroupName         string  `json:"group_name"`
	Count             int32   `json:"count"`
	AvgHba1c          float64 `json:"avg_hba1c"`
	AvgFbs            float64 `json:"avg_fbs"`
	AvgBmi            float64 `json:"avg_bmi"`
	AvgBpSystolic     float64 `json:"avg_bp_systolic"`
	AvgBpDiastolic    float64 `json:"avg_bp_diastolic"`
	AvgRiskScore      float64 `json:"avg_risk_score"`
	LowRiskCount      int32   `json:"low_risk_count"`
	ModerateRiskCount int32   `json:"moderate_risk_count"`
	HighRiskCount     int32   `json:"high_risk_count"`
}

// cohort.sql: SQLC queries for cohort analysis and aggregate statistics
func (q *Queries) CohortStatsByCluster(ctx context.Context) ([]CohortStatsByClusterRow, error) {
	rows, err := q.db.Query(ctx, cohortStatsByCluster)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CohortStatsByClusterRow
	for rows.Next() {
		var i CohortStatsByClusterRow
		if err := rows.Scan(
			&i.GroupName,
			&i.Count,
			&i.AvgHba1c,
			&i.AvgFbs,
			&i.AvgBmi,
			&i.AvgBpSystolic,
			&i.AvgBpDiastolic,
			&i.AvgRiskScore,
			&i.LowRiskCount,
			&i.ModerateRiskCount,
			&i.HighRiskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cohortStatsByMenopauseStatus = `-- name: CohortStatsByMenopauseStatus :many
SELECT 
    COALESCE(u.menopause_status, 'Unknown') AS group_name,
    COUNT(*)::int AS count,
    COALESCE(AVG(a.hba1c), 0)::float8 AS avg_hba1c,
    COALESCE(AVG(a.fbs), 0)::float8 AS avg_fbs,
    COALESCE(AVG(a.bmi), 0)::float8 AS avg_bmi,
    COALESCE(AVG(a.systolic), 0)::float8 AS avg_bp_systolic,
    COALESCE(AVG(a.diastolic), 0)::float8 AS avg_bp_diastolic,
    COALESCE(AVG(a.risk_score), 0)::float8 AS avg_risk_score
FROM assessments a
JOIN users u ON a.user_id = u.id
GROUP BY 1
`

type CohortStatsByMenopauseStatusRow struct {
	GroupName      string  `json:"group_name"`
	Count          int32   `json:"count"`
	AvgHba1c       float64 `json:"avg_hba1c"`
	AvgFbs         float64 `json:"avg_fbs"`
	AvgBmi         float64 `json:"avg_bmi"`
	AvgBpSystolic  float64 `json:"avg_bp_systolic"`
	AvgBpDiastolic float64 `json:"avg_bp_diastolic"`
	AvgRiskScore   float64 `json:"avg_risk_score"`
}

func (q *Queries) CohortStatsByMenopauseStatus(ctx context.Context) ([]CohortStatsByMenopauseStatusRow, error) {
	rows, err := q.db.Query(ctx, cohortStatsByMenopauseStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CohortStatsByMenopauseStatusRow
	for rows.Next() {
		var i CohortStatsByMenopauseStatusRow
		if err := rows.Scan(
			&i.GroupName,
			&i.Count,
			&i.AvgHba1c,
			&i.AvgFbs,
			&i.AvgBmi,
			&i.AvgBpSystolic,
			&i.AvgBpDiastolic,
			&i.AvgRiskScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cohortStatsByRiskLevel = `-- name: CohortStatsByRiskLevel :many
SELECT 
    CASE 
        WHEN risk_score < 30 THEN 'Low'
        WHEN risk_score >= 30 AND risk_score < 70 THEN 'Moderate'
        ELSE 'High'
    END AS group_name,
    COUNT(*)::int AS count,
    COALESCE(AVG(hba1c), 0)::float8 AS avg_hba1c,
    COALESCE(AVG(fbs), 0)::float8 AS avg_fbs,
    COALESCE(AVG(bmi), 0)::float8 AS avg_bmi,
    COALESCE(AVG(systolic), 0)::float8 AS avg_bp_systolic,
    COALESCE(AVG(diastolic), 0)::float8 AS avg_bp_diastolic,
    COALESCE(AVG(risk_score), 0)::float8 AS avg_risk_score
FROM assessments
GROUP BY 
    CASE 
        WHEN risk_score < 30 THEN 'Low'
        WHEN risk_score >= 30 AND risk_score < 70 THEN 'Moderate'
        ELSE 'High'
    END
`

type CohortStatsByRiskLevelRow struct {
	GroupName      string  `json:"group_name"`
	Count          int32   `json:"count"`
	AvgHba1c       float64 `json:"avg_hba1c"`
	AvgFbs         float64 `json:"avg_fbs"`
	AvgBmi         float64 `json:"avg_bmi"`
	AvgBpSystolic  float64 `json:"avg_bp_systolic"`
	AvgBpDiastolic float64 `json:"avg_bp_diastolic"`
	AvgRiskScore   float64 `json:"avg_risk_score"`
}

func (q *Queries) CohortStatsByRiskLevel(ctx context.Context) ([]CohortStatsByRiskLevelRow, error) {
	rows, err := q.db.Query(ctx, cohortStatsByRiskLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CohortStatsByRiskLevelRow
	for rows.Next() {
		var i CohortStatsByRiskLevelRow
		if err := rows.Scan(
			&i.GroupName,
			&i.Count,
			&i.AvgHba1c,
			&i.AvgFbs,
			&i.AvgBmi,
			&i.AvgBpSystolic,
			&i.AvgBpDiastolic,
			&i.AvgRiskScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalAssessmentCount = `-- name: TotalAssessmentCount :one
SELECT COUNT(*)::int AS count FROM assessments
`

func (q *Queries) TotalAssessmentCount(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, totalAssessmentCount)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const totalPatientCount = `-- name: TotalPatientCount :one
SELECT COUNT(*)::int AS count FROM users WHERE role = 'patient'
`

func (q *Queries) TotalPatientCount(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, totalPatientCount)
	var count int32
	err := row.Scan(&count)
	return count, err
}
