// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Assessment struct {
	ID               int32              `json:"id"`
	PatientID        pgtype.Int4        `json:"patient_id"`
	Fbs              pgtype.Numeric     `json:"fbs"`
	Hba1c            pgtype.Numeric     `json:"hba1c"`
	Cholesterol      pgtype.Int4        `json:"cholesterol"`
	Ldl              pgtype.Int4        `json:"ldl"`
	Hdl              pgtype.Int4        `json:"hdl"`
	Triglycerides    pgtype.Int4        `json:"triglycerides"`
	Systolic         pgtype.Int4        `json:"systolic"`
	Diastolic        pgtype.Int4        `json:"diastolic"`
	Activity         pgtype.Text        `json:"activity"`
	HistoryFlag      pgtype.Bool        `json:"history_flag"`
	Smoking          pgtype.Text        `json:"smoking"`
	Hypertension     pgtype.Text        `json:"hypertension"`
	HeartDisease     pgtype.Text        `json:"heart_disease"`
	Bmi              pgtype.Numeric     `json:"bmi"`
	Cluster          pgtype.Text        `json:"cluster"`
	RiskScore        pgtype.Int4        `json:"risk_score"`
	ModelVersion     pgtype.Text        `json:"model_version"`
	DatasetHash      pgtype.Text        `json:"dataset_hash"`
	ValidationStatus pgtype.Text        `json:"validation_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AuditEvent struct {
	ID         int32              `json:"id"`
	Actor      pgtype.Text        `json:"actor"`
	Action     pgtype.Text        `json:"action"`
	TargetType pgtype.Text        `json:"target_type"`
	TargetID   pgtype.Int4        `json:"target_id"`
	Details    []byte             `json:"details"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Clinic struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Address   pgtype.Text        `json:"address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ModelRun struct {
	ID           int32              `json:"id"`
	ModelVersion string             `json:"model_version"`
	DatasetHash  pgtype.Text        `json:"dataset_hash"`
	Notes        pgtype.Text        `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Patient struct {
	ID              int32              `json:"id"`
	Name            string             `json:"name"`
	Age             pgtype.Int4        `json:"age"`
	MenopauseStatus pgtype.Text        `json:"menopause_status"`
	YearsMenopause  pgtype.Int4        `json:"years_menopause"`
	Bmi             pgtype.Numeric     `json:"bmi"`
	BpSystolic      pgtype.Int4        `json:"bp_systolic"`
	BpDiastolic     pgtype.Int4        `json:"bp_diastolic"`
	Activity        pgtype.Text        `json:"activity"`
	Smoking         pgtype.Text        `json:"smoking"`
	Hypertension    pgtype.Text        `json:"hypertension"`
	HeartDisease    pgtype.Text        `json:"heart_disease"`
	Chol            pgtype.Int4        `json:"chol"`
	Ldl             pgtype.Int4        `json:"ldl"`
	Hdl             pgtype.Int4        `json:"hdl"`
	Triglycerides   pgtype.Int4        `json:"triglycerides"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FamilyHistory   pgtype.Bool        `json:"family_history"`
	PhysActivity    pgtype.Bool        `json:"phys_activity"`
	UserID          int32              `json:"user_id"`
}

type RefreshToken struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   bool               `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type User struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserClinic struct {
	UserID    int32              `json:"user_id"`
	ClinicID  int32              `json:"clinic_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
