// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_runs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countModelRuns = `-- name: CountModelRuns :one
SELECT COUNT(*) FROM model_runs
`

func (q *Queries) CountModelRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countModelRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createModelRun = `-- name: CreateModelRun :one
INSERT INTO model_runs (model_version, dataset_hash, notes, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, model_version, dataset_hash, notes, created_at
`

type CreateModelRunParams struct {
	ModelVersion string      `json:"model_version"`
	DatasetHash  pgtype.Text `json:"dataset_hash"`
	Notes        pgtype.Text `json:"notes"`
}

func (q *Queries) CreateModelRun(ctx context.Context, arg CreateModelRunParams) (ModelRun, error) {
	row := q.db.QueryRow(ctx, createModelRun, arg.ModelVersion, arg.DatasetHash, arg.Notes)
	var i ModelRun
	err := row.Scan(
		&i.ID,
		&i.ModelVersion,
		&i.DatasetHash,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestModelRun = `-- name: GetLatestModelRun :one
SELECT id, model_version, dataset_hash, notes, created_at
FROM model_runs
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestModelRun(ctx context.Context) (ModelRun, error) {
	row := q.db.QueryRow(ctx, getLatestModelRun)
	var i ModelRun
	err := row.Scan(
		&i.ID,
		&i.ModelVersion,
		&i.DatasetHash,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getModelRunByVersion = `-- name: GetModelRunByVersion :one
SELECT id, model_version, dataset_hash, notes, created_at
FROM model_runs
WHERE model_version = $1
LIMIT 1
`

func (q *Queries) GetModelRunByVersion(ctx context.Context, modelVersion string) (ModelRun, error) {
	row := q.db.QueryRow(ctx, getModelRunByVersion, modelVersion)
	var i ModelRun
	err := row.Scan(
		&i.ID,
		&i.ModelVersion,
		&i.DatasetHash,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listModelRuns = `-- name: ListModelRuns :many
SELECT id, model_version, dataset_hash, notes, created_at
FROM model_runs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListModelRunsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListModelRuns(ctx context.Context, arg ListModelRunsParams) ([]ModelRun, error) {
	rows, err := q.db.Query(ctx, listModelRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelRun
	for rows.Next() {
		var i ModelRun
		if err := rows.Scan(
			&i.ID,
			&i.ModelVersion,
			&i.DatasetHash,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
