// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patients.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPatientsByUser = `-- name: CountPatientsByUser :one
SELECT COUNT(*) FROM patients WHERE user_id = $1
`

func (q *Queries) CountPatientsByUser(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countPatientsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (
  user_id, name, age, menopause_status, years_menopause, bmi, bp_systolic, bp_diastolic,
  activity, phys_activity, smoking, hypertension, heart_disease, family_history, chol, ldl, hdl, triglycerides
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8,
  $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
RETURNING id, user_id, name, age, menopause_status, years_menopause, bmi, bp_systolic, bp_diastolic,
          activity, phys_activity, smoking, hypertension, heart_disease, family_history, chol, ldl, hdl, triglycerides,
          created_at, updated_at
`

type CreatePatientParams struct {
	UserID          int32          `json:"user_id"`
	Name            string         `json:"name"`
	Age             pgtype.Int4    `json:"age"`
	MenopauseStatus pgtype.Text    `json:"menopause_status"`
	YearsMenopause  pgtype.Int4    `json:"years_menopause"`
	Bmi             pgtype.Numeric `json:"bmi"`
	BpSystolic      pgtype.Int4    `json:"bp_systolic"`
	BpDiastolic     pgtype.Int4    `json:"bp_diastolic"`
	Activity        pgtype.Text    `json:"activity"`
	PhysActivity    pgtype.Bool    `json:"phys_activity"`
	Smoking         pgtype.Text    `json:"smoking"`
	Hypertension    pgtype.Text    `json:"hypertension"`
	HeartDisease    pgtype.Text    `json:"heart_disease"`
	FamilyHistory   pgtype.Bool    `json:"family_history"`
	Chol            pgtype.Int4    `json:"chol"`
	Ldl             pgtype.Int4    `json:"ldl"`
	Hdl             pgtype.Int4    `json:"hdl"`
	Triglycerides   pgtype.Int4    `json:"triglycerides"`
}

type CreatePatientRow struct {
	ID              int32              `json:"id"`
	UserID          int32              `json:"user_id"`
	Name            string             `json:"name"`
	Age             pgtype.Int4        `json:"age"`
	MenopauseStatus pgtype.Text        `json:"menopause_status"`
	YearsMenopause  pgtype.Int4        `json:"years_menopause"`
	Bmi             pgtype.Numeric     `json:"bmi"`
	BpSystolic      pgtype.Int4        `json:"bp_systolic"`
	BpDiastolic     pgtype.Int4        `json:"bp_diastolic"`
	Activity        pgtype.Text        `json:"activity"`
	PhysActivity    pgtype.Bool        `json:"phys_activity"`
	Smoking         pgtype.Text        `json:"smoking"`
	Hypertension    pgtype.Text        `json:"hypertension"`
	HeartDisease    pgtype.Text        `json:"heart_disease"`
	FamilyHistory   pgtype.Bool        `json:"family_history"`
	Chol            pgtype.Int4        `json:"chol"`
	Ldl             pgtype.Int4        `json:"ldl"`
	Hdl             pgtype.Int4        `json:"hdl"`
	Triglycerides   pgtype.Int4        `json:"triglycerides"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (CreatePatientRow, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.UserID,
		arg.Name,
		arg.Age,
		arg.MenopauseStatus,
		arg.YearsMenopause,
		arg.Bmi,
		arg.BpSystolic,
		arg.BpDiastolic,
		arg.Activity,
		arg.PhysActivity,
		arg.Smoking,
		arg.Hypertension,
		arg.HeartDisease,
		arg.FamilyHistory,
		arg.Chol,
		arg.Ldl,
		arg.Hdl,
		arg.Triglycerides,
	)
	var i CreatePatientRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Age,
		&i.MenopauseStatus,
		&i.YearsMenopause,
		&i.Bmi,
		&i.BpSystolic,
		&i.BpDiastolic,
		&i.Activity,
		&i.PhysActivity,
		&i.Smoking,
		&i.Hypertension,
		&i.HeartDisease,
		&i.FamilyHistory,
		&i.Chol,
		&i.Ldl,
		&i.Hdl,
		&i.Triglycerides,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePatient = `-- name: DeletePatient :exec
DELETE FROM patients
WHERE id = $1 AND user_id = $2
`

type DeletePatientParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeletePatient(ctx context.Context, arg DeletePatientParams) error {
	_, err := q.db.Exec(ctx, deletePatient, arg.ID, arg.UserID)
	return err
}

const getPatient = `-- name: GetPatient :one
SELECT id, user_id, name, age, menopause_status, years_menopause, bmi, bp_systolic, bp_diastolic,
       activity, phys_activity, smoking, hypertension, heart_disease, family_history, chol, ldl, hdl, triglycerides,
       created_at, updated_at
FROM patients
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetPatientParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetPatientRow struct {
	ID              int32              `json:"id"`
	UserID          int32              `json:"user_id"`
	Name            string             `json:"name"`
	Age             pgtype.Int4        `json:"age"`
	MenopauseStatus pgtype.Text        `json:"menopause_status"`
	YearsMenopause  pgtype.Int4        `json:"years_menopause"`
	Bmi             pgtype.Numeric     `json:"bmi"`
	BpSystolic      pgtype.Int4        `json:"bp_systolic"`
	BpDiastolic     pgtype.Int4        `json:"bp_diastolic"`
	Activity        pgtype.Text        `json:"activity"`
	PhysActivity    pgtype.Bool        `json:"phys_activity"`
	Smoking         pgtype.Text        `json:"smoking"`
	Hypertension    pgtype.Text        `json:"hypertension"`
	HeartDisease    pgtype.Text        `json:"heart_disease"`
	FamilyHistory   pgtype.Bool        `json:"family_history"`
	Chol            pgtype.Int4        `json:"chol"`
	Ldl             pgtype.Int4        `json:"ldl"`
	Hdl             pgtype.Int4        `json:"hdl"`
	Triglycerides   pgtype.Int4        `json:"triglycerides"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPatient(ctx context.Context, arg GetPatientParams) (GetPatientRow, error) {
	row := q.db.QueryRow(ctx, getPatient, arg.ID, arg.UserID)
	var i GetPatientRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Age,
		&i.MenopauseStatus,
		&i.YearsMenopause,
		&i.Bmi,
		&i.BpSystolic,
		&i.BpDiastolic,
		&i.Activity,
		&i.PhysActivity,
		&i.Smoking,
		&i.Hypertension,
		&i.HeartDisease,
		&i.FamilyHistory,
		&i.Chol,
		&i.Ldl,
		&i.Hdl,
		&i.Triglycerides,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPatients = `-- name: ListPatients :many
SELECT id, user_id, name, age, menopause_status, years_menopause, bmi, bp_systolic, bp_diastolic,
       activity, phys_activity, smoking, hypertension, heart_disease, family_history, chol, ldl, hdl, triglycerides,
       created_at, updated_at
FROM patients
WHERE user_id = $1
ORDER BY id DESC
`

type ListPatientsRow struct {
	ID              int32              `json:"id"`
	UserID          int32              `json:"user_id"`
	Name            string             `json:"name"`
	Age             pgtype.Int4        `json:"age"`
	MenopauseStatus pgtype.Text        `json:"menopause_status"`
	YearsMenopause  pgtype.Int4        `json:"years_menopause"`
	Bmi             pgtype.Numeric     `json:"bmi"`
	BpSystolic      pgtype.Int4        `json:"bp_systolic"`
	BpDiastolic     pgtype.Int4        `json:"bp_diastolic"`
	Activity        pgtype.Text        `json:"activity"`
	PhysActivity    pgtype.Bool        `json:"phys_activity"`
	Smoking         pgtype.Text        `json:"smoking"`
	Hypertension    pgtype.Text        `json:"hypertension"`
	HeartDisease    pgtype.Text        `json:"heart_disease"`
	FamilyHistory   pgtype.Bool        `json:"family_history"`
	Chol            pgtype.Int4        `json:"chol"`
	Ldl             pgtype.Int4        `json:"ldl"`
	Hdl             pgtype.Int4        `json:"hdl"`
	Triglycerides   pgtype.Int4        `json:"triglycerides"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// patients.sql: sqlc queries for patient CRUD/listing used by the Postgres store.
func (q *Queries) ListPatients(ctx context.Context, userID int32) ([]ListPatientsRow, error) {
	rows, err := q.db.Query(ctx, listPatients, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatientsRow
	for rows.Next() {
		var i ListPatientsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Age,
			&i.MenopauseStatus,
			&i.YearsMenopause,
			&i.Bmi,
			&i.BpSystolic,
			&i.BpDiastolic,
			&i.Activity,
			&i.PhysActivity,
			&i.Smoking,
			&i.Hypertension,
			&i.HeartDisease,
			&i.FamilyHistory,
			&i.Chol,
			&i.Ldl,
			&i.Hdl,
			&i.Triglycerides,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientsLimited = `-- name: ListPatientsLimited :many
SELECT id, user_id, name, age, menopause_status, years_menopause, bmi, bp_systolic, bp_diastolic,
       activity, phys_activity, smoking, hypertension, heart_disease, family_history, chol, ldl, hdl, triglycerides,
       created_at, updated_at
FROM patients
WHERE user_id = $1
ORDER BY id DESC
LIMIT $2
`

type ListPatientsLimitedParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type ListPatientsLimitedRow struct {
	ID              int32              `json:"id"`
	UserID          int32              `json:"user_id"`
	Name            string             `json:"name"`
	Age             pgtype.Int4        `json:"age"`
	MenopauseStatus pgtype.Text        `json:"menopause_status"`
	YearsMenopause  pgtype.Int4        `json:"years_menopause"`
	Bmi             pgtype.Numeric     `json:"bmi"`
	BpSystolic      pgtype.Int4        `json:"bp_systolic"`
	BpDiastolic     pgtype.Int4        `json:"bp_diastolic"`
	Activity        pgtype.Text        `json:"activity"`
	PhysActivity    pgtype.Bool        `json:"phys_activity"`
	Smoking         pgtype.Text        `json:"smoking"`
	Hypertension    pgtype.Text        `json:"hypertension"`
	HeartDisease    pgtype.Text        `json:"heart_disease"`
	FamilyHistory   pgtype.Bool        `json:"family_history"`
	Chol            pgtype.Int4        `json:"chol"`
	Ldl             pgtype.Int4        `json:"ldl"`
	Hdl             pgtype.Int4        `json:"hdl"`
	Triglycerides   pgtype.Int4        `json:"triglycerides"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPatientsLimited(ctx context.Context, arg ListPatientsLimitedParams) ([]ListPatientsLimitedRow, error) {
	rows, err := q.db.Query(ctx, listPatientsLimited, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatientsLimitedRow
	for rows.Next() {
		var i ListPatientsLimitedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Age,
			&i.MenopauseStatus,
			&i.YearsMenopause,
			&i.Bmi,
			&i.BpSystolic,
			&i.BpDiastolic,
			&i.Activity,
			&i.PhysActivity,
			&i.Smoking,
			&i.Hypertension,
			&i.HeartDisease,
			&i.FamilyHistory,
			&i.Chol,
			&i.Ldl,
			&i.Hdl,
			&i.Triglycerides,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientsPaginated = `-- name: ListPatientsPaginated :many
SELECT id, user_id, name, age, menopause_status, years_menopause, bmi, bp_systolic, bp_diastolic,
       activity, phys_activity, smoking, hypertension, heart_disease, family_history, chol, ldl, hdl, triglycerides,
       created_at, updated_at
FROM patients
WHERE user_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListPatientsPaginatedParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPatientsPaginatedRow struct {
	ID              int32              `json:"id"`
	UserID          int32              `json:"user_id"`
	Name            string             `json:"name"`
	Age             pgtype.Int4        `json:"age"`
	MenopauseStatus pgtype.Text        `json:"menopause_status"`
	YearsMenopause  pgtype.Int4        `json:"years_menopause"`
	Bmi             pgtype.Numeric     `json:"bmi"`
	BpSystolic      pgtype.Int4        `json:"bp_systolic"`
	BpDiastolic     pgtype.Int4        `json:"bp_diastolic"`
	Activity        pgtype.Text        `json:"activity"`
	PhysActivity    pgtype.Bool        `json:"phys_activity"`
	Smoking         pgtype.Text        `json:"smoking"`
	Hypertension    pgtype.Text        `json:"hypertension"`
	HeartDisease    pgtype.Text        `json:"heart_disease"`
	FamilyHistory   pgtype.Bool        `json:"family_history"`
	Chol            pgtype.Int4        `json:"chol"`
	Ldl             pgtype.Int4        `json:"ldl"`
	Hdl             pgtype.Int4        `json:"hdl"`
	Triglycerides   pgtype.Int4        `json:"triglycerides"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPatientsPaginated(ctx context.Context, arg ListPatientsPaginatedParams) ([]ListPatientsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listPatientsPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatientsPaginatedRow
	for rows.Next() {
		var i ListPatientsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Age,
			&i.MenopauseStatus,
			&i.YearsMenopause,
			&i.Bmi,
			&i.BpSystolic,
			&i.BpDiastolic,
			&i.Activity,
			&i.PhysActivity,
			&i.Smoking,
			&i.Hypertension,
			&i.HeartDisease,
			&i.FamilyHistory,
			&i.Chol,
			&i.Ldl,
			&i.Hdl,
			&i.Triglycerides,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientsWithLatestAssessment = `-- name: ListPatientsWithLatestAssessment :many
SELECT 
    p.id, p.user_id, p.name, p.age, p.menopause_status, p.years_menopause, 
    p.bmi, p.bp_systolic, p.bp_diastolic, p.activity, p.phys_activity, 
    p.smoking, p.hypertension, p.heart_disease, p.family_history, 
    p.chol, p.ldl, p.hdl, p.triglycerides, p.created_at, p.updated_at,
    COALESCE(la.cluster, '') AS latest_cluster,
    COALESCE(la.risk_score, 0) AS latest_risk_score,
    COALESCE(la.fbs, 0) AS latest_fbs,
    COALESCE(la.hba1c, 0) AS latest_hba1c,
    la.created_at AS latest_assessment_at
FROM patients p
LEFT JOIN LATERAL (
    SELECT a.cluster, a.risk_score, a.fbs, a.hba1c, a.created_at
    FROM assessments a
    WHERE a.patient_id = p.id
    ORDER BY a.created_at DESC
    LIMIT 1
) la ON true
WHERE p.user_id = $1
ORDER BY p.id DESC
`

type ListPatientsWithLatestAssessmentRow struct {
	ID                 int32              `json:"id"`
	UserID             int32              `json:"user_id"`
	Name               string             `json:"name"`
	Age                pgtype.Int4        `json:"age"`
	MenopauseStatus    pgtype.Text        `json:"menopause_status"`
	YearsMenopause     pgtype.Int4        `json:"years_menopause"`
	Bmi                pgtype.Numeric     `json:"bmi"`
	BpSystolic         pgtype.Int4        `json:"bp_systolic"`
	BpDiastolic        pgtype.Int4        `json:"bp_diastolic"`
	Activity           pgtype.Text        `json:"activity"`
	PhysActivity       pgtype.Bool        `json:"phys_activity"`
	Smoking            pgtype.Text        `json:"smoking"`
	Hypertension       pgtype.Text        `json:"hypertension"`
	HeartDisease       pgtype.Text        `json:"heart_disease"`
	FamilyHistory      pgtype.Bool        `json:"family_history"`
	Chol               pgtype.Int4        `json:"chol"`
	Ldl                pgtype.Int4        `json:"ldl"`
	Hdl                pgtype.Int4        `json:"hdl"`
	Triglycerides      pgtype.Int4        `json:"triglycerides"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	LatestCluster      string             `json:"latest_cluster"`
	LatestRiskScore    int32              `json:"latest_risk_score"`
	LatestFbs          pgtype.Numeric     `json:"latest_fbs"`
	LatestHba1c        pgtype.Numeric     `json:"latest_hba1c"`
	LatestAssessmentAt pgtype.Timestamptz `json:"latest_assessment_at"`
}

func (q *Queries) ListPatientsWithLatestAssessment(ctx context.Context, userID int32) ([]ListPatientsWithLatestAssessmentRow, error) {
	rows, err := q.db.Query(ctx, listPatientsWithLatestAssessment, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatientsWithLatestAssessmentRow
	for rows.Next() {
		var i ListPatientsWithLatestAssessmentRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Age,
			&i.MenopauseStatus,
			&i.YearsMenopause,
			&i.Bmi,
			&i.BpSystolic,
			&i.BpDiastolic,
			&i.Activity,
			&i.PhysActivity,
			&i.Smoking,
			&i.Hypertension,
			&i.HeartDisease,
			&i.FamilyHistory,
			&i.Chol,
			&i.Ldl,
			&i.Hdl,
			&i.Triglycerides,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestCluster,
			&i.LatestRiskScore,
			&i.LatestFbs,
			&i.LatestHba1c,
			&i.LatestAssessmentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatient = `-- name: UpdatePatient :one
UPDATE patients
SET name = $3,
    age = $4,
    menopause_status = $5,
    years_menopause = $6,
    bmi = $7,
    bp_systolic = $8,
    bp_diastolic = $9,
    activity = $10,
    phys_activity = $11,
    smoking = $12,
    hypertension = $13,
    heart_disease = $14,
    family_history = $15,
    chol = $16,
    ldl = $17,
    hdl = $18,
    triglycerides = $19,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, age, menopause_status, years_menopause, bmi, bp_systolic, bp_diastolic,
          activity, phys_activity, smoking, hypertension, heart_disease, family_history, chol, ldl, hdl, triglycerides,
          created_at, updated_at
`

type UpdatePatientParams struct {
	ID              int32          `json:"id"`
	UserID          int32          `json:"user_id"`
	Name            string         `json:"name"`
	Age             pgtype.Int4    `json:"age"`
	MenopauseStatus pgtype.Text    `json:"menopause_status"`
	YearsMenopause  pgtype.Int4    `json:"years_menopause"`
	Bmi             pgtype.Numeric `json:"bmi"`
	BpSystolic      pgtype.Int4    `json:"bp_systolic"`
	BpDiastolic     pgtype.Int4    `json:"bp_diastolic"`
	Activity        pgtype.Text    `json:"activity"`
	PhysActivity    pgtype.Bool    `json:"phys_activity"`
	Smoking         pgtype.Text    `json:"smoking"`
	Hypertension    pgtype.Text    `json:"hypertension"`
	HeartDisease    pgtype.Text    `json:"heart_disease"`
	FamilyHistory   pgtype.Bool    `json:"family_history"`
	Chol            pgtype.Int4    `json:"chol"`
	Ldl             pgtype.Int4    `json:"ldl"`
	Hdl             pgtype.Int4    `json:"hdl"`
	Triglycerides   pgtype.Int4    `json:"triglycerides"`
}

type UpdatePatientRow struct {
	ID              int32              `json:"id"`
	UserID          int32              `json:"user_id"`
	Name            string             `json:"name"`
	Age             pgtype.Int4        `json:"age"`
	MenopauseStatus pgtype.Text        `json:"menopause_status"`
	YearsMenopause  pgtype.Int4        `json:"years_menopause"`
	Bmi             pgtype.Numeric     `json:"bmi"`
	BpSystolic      pgtype.Int4        `json:"bp_systolic"`
	BpDiastolic     pgtype.Int4        `json:"bp_diastolic"`
	Activity        pgtype.Text        `json:"activity"`
	PhysActivity    pgtype.Bool        `json:"phys_activity"`
	Smoking         pgtype.Text        `json:"smoking"`
	Hypertension    pgtype.Text        `json:"hypertension"`
	HeartDisease    pgtype.Text        `json:"heart_disease"`
	FamilyHistory   pgtype.Bool        `json:"family_history"`
	Chol            pgtype.Int4        `json:"chol"`
	Ldl             pgtype.Int4        `json:"ldl"`
	Hdl             pgtype.Int4        `json:"hdl"`
	Triglycerides   pgtype.Int4        `json:"triglycerides"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) (UpdatePatientRow, error) {
	row := q.db.QueryRow(ctx, updatePatient,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Age,
		arg.MenopauseStatus,
		arg.YearsMenopause,
		arg.Bmi,
		arg.BpSystolic,
		arg.BpDiastolic,
		arg.Activity,
		arg.PhysActivity,
		arg.Smoking,
		arg.Hypertension,
		arg.HeartDisease,
		arg.FamilyHistory,
		arg.Chol,
		arg.Ldl,
		arg.Hdl,
		arg.Triglycerides,
	)
	var i UpdatePatientRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Age,
		&i.MenopauseStatus,
		&i.YearsMenopause,
		&i.Bmi,
		&i.BpSystolic,
		&i.BpDiastolic,
		&i.Activity,
		&i.PhysActivity,
		&i.Smoking,
		&i.Hypertension,
		&i.HeartDisease,
		&i.FamilyHistory,
		&i.Chol,
		&i.Ldl,
		&i.Hdl,
		&i.Triglycerides,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
